sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t godsmith/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true godsmith/docker-react yarn test
