FROM docker.io/node:alpine

WORKDIR '/app'

COPY package.json ./
RUN npm install

# The following line is necessary to prevent "EACCES: permission denied, mkdir /app/node_modules/.cache"
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache 

COPY . .

CMD ["npm", "run", "start"]
